# Generated by Django 3.2.6 on 2021-08-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=14, verbose_name='cnpj'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome_fantasia',
            field=models.CharField(max_length=50, verbose_name='nome_empresa'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='descricao',
            field=models.TextField(verbose_name='descricao'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='descricao',
            field=models.TextField(verbose_name='descricao'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='salario',
            field=models.FloatField(verbose_name='salario'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.BooleanField(default=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='tipo_contrato',
            field=models.CharField(choices=[('PJ', 'Pessoa Jurídica'), ('CLT', 'Consolidação das Leis do Trabalho')], max_length=50, verbose_name='tipo_contrato'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='titulo',
            field=models.CharField(max_length=30, verbose_name='titulo'),
        ),
    ]
